### PR TITLE
Make Firmafon send JSON back for every endpoint.

### PR DESCRIPTION
**Pull request by henrikbjorn**
``` bash
$ curl -H "Accept: application/json" https://app.firmafon.dk/api/v2/ost
$ {"status":"404","error":"Not Found"}
```

### CODE REVIEW

**Comment by steffen25** [comment]
Hey @henrikbjorn Thank you for the PR, It is hereby merged.

**Comment by kaspth** [comment]
Hey @steffen25, just to be clear: passing along this Accept header will tune our API to always respond in JSON.

So if you hit an endpoint that doesn't exist you won't get HTML back, you'll get what you've told us you Accept: JSON 😄

**Comment by steffen25** [comment]
Hey @kaspth Why haven’t I thought of that oh well thanks for pointing that out 👍

**Comment by kaspth** [comment]
No problem and thanks for doing the wrapper! Looks like it's almost a Go 😋

**Comment by steffen25** [comment]
@kaspth Haha :) Yes I still have to implement some endpoints etc before a release or someone would find it useable to use within their application. 

What about you guys have any of you tried go?

**Comment by kaspth** [comment]
Nice! I haven't tried it, but @henrikbjorn has used it beforehand 😊

**Comment by steffen25** [comment]
Okay cool :)

**Pull request merged**
